version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13
  aws-s3: circleci/aws-s3@1.0.11

jobs:
  prebuild:
    working_directory: ~/workspace
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - run: sudo apt update && sudo apt install -y jq
      - run: aws ssm get-parameter --name portals-me-client-stg-env --with-decryption --region ap-northeast-1 | jq -r '.Parameter.Value' > .env.production
      - persist_to_workspace:
          root: .
          paths:
            - .
  build:
    working_directory: ~/workspace
    docker:
      - image: node
    steps:
      - attach_workspace:
          at: .
      - run: npm i -g yarn
      - run: yarn && yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    working_directory: ~/workspace
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/install
      - aws-s3/sync:
          from: dist
          to: "s3://portals-me-stg/"
          arguments: --acl public-read
          overwrite: true

workflows:
  version: 2
  deploy:
    jobs:
      - prebuild:
          filters:
            branches:
              only: master
          context: aws
      - build:
          requires:
            - prebuild
      - deploy:
          requires:
            - build
          context: aws
