version: 2

jobs:
  deploy:
    docker:
      - image: node
    steps:
      - checkout
      - run: apt update && apt install -y python3 python3-pip jq
      - run: pip3 install awscli
      - run: aws ssm get-parameter --name portals-me-client-stg-env --with-decryption | jq '.Parameter.Value' > .env.production
      - run: yarn && yarn build && aws s3 sync dist s3://portals-me-stg/ --acl public-read

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
