version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

jobs:
  deploy:
    docker:
      - image: node
    steps:
      - checkout
      - aws-cli/install
      - run: apt update && apt install -y jq
      - run: aws ssm get-parameter --name portals-me-client-stg-env --with-decryption | jq '.Parameter.Value' > .env.production
      - run: yarn && yarn build
      - aws-s3/sync:
          from: dist
          to: "s3://portals-me-stg/"
          arguments: --acl public-read
          overwrite: true

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
          context: aws
