version: 2

jobs:
  deploy:
    docker:
      - image: node
    steps:
      - checkout
      - run: apt update && apt install -y python3 python3-pip
      - run: pip3 install awscli
      - run: yarn && yarn build && aws s3 sync dist s3://portals-me-stg/ --acl public-read
  notify-approval:
    docker:
      - image: node
    steps:
      - run: |
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": \"[portals-me-front] Please approve workflow from <https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}|here>.\"}" \
            $SLACK_WEBHOOK_URL

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
      - notify-approval:
          requires:
            - deploy-stg
      - approval:
          type: approval
          requires:
            - notify-approval
